/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LazyImg: typeof import('./../components/common/LazyImg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheBox: typeof import('./../components/common/TheBox.vue')['default']
    TheFooter: typeof import('./../components/TheFooter.vue')['default']
  }
}
